CREATE TABLE [dbo].[All Clean Data] (
[ORG_NAME] varchar(100),
[BATCH_NUM] varchar(10),
[OFF_ASS_NUM] varchar(10),
[OFF_BR_NUM] varchar(10),
[Y_MEMB_ID] varchar(50),
[Y_FAM_ID] varchar(50),
[FIRST_NAME] varchar(50),
[MID_NAME] varchar(50),
[LAST_NAME] varchar(50),
[SUFFIX] varchar(20),
[FULL_NAME] varchar(100),
[ADDRESS1] varchar(50),
[ADDRESS2] varchar(50),
[CITY] varchar(50),
[STATE] varchar(50),
[ZIP] varchar(20),
[COUNTRY] varchar(50),
[LAST_LINE] varchar(50),
[PHONE] varchar(50),
[HHH_IND] varchar(50),
[DOB] varchar(50),
[JOIN_DATE] varchar(50),
[GENDER] varchar(10),
[CATEGORY] varchar(50),
[MEMBER_TYPE] varchar(50),
[STAFF_TYPE] varchar(50),
[BILL_MEMB] varchar(50),
[HH_ID] varchar(50),
[EMAIL] varchar(50),
[EMPLOYEE] varchar(50),
[DONOR] varchar(50),
[PROGRAM_MEMBER] varchar(50),
[Program_Type] varchar(50),
[Program_Site_Location] varchar(50),
[NEW_MEMBER] varchar(50),
[ACTIVE] varchar(50),
[REMOVAL_REASON] varchar(50),
[FULL_TIME PART_TIME] varchar(50),
[HOURLY SALARY] varchar(50),
[ETHNICITY] varchar(50),
[COMMENTS] varchar(50),
[SITE_NUMBER] varchar(50),
[GROUP_NAME] varchar(50),
[GROUP_NUMBER] varchar(50)
) ON TRXGROUP