CREATE TABLE [Crisp] (
[Organization Name] varchar(75) DEFAULT '',
[Organization Number] varchar(10) DEFAULT '',
[Association Name] varchar(100) DEFAULT '',
[Association Number] varchar(10) DEFAULT '',
[Association Address 1] varchar(50) DEFAULT '',
[Association Address 2] varchar(50) DEFAULT '',
[Association City] varchar(50) DEFAULT '',
[Association State] varchar(50) DEFAULT '',
[Association Zip] varchar(20) DEFAULT '',
[Official Branch Name] varchar(100) DEFAULT '',
[Official Branch Number] varchar(10) DEFAULT '',
[Branch Address 1] varchar(50) DEFAULT '',
[Branch Address 2] varchar(50) DEFAULT '',
[Branch City] varchar(50) DEFAULT '',
[Branch State] varchar(50) DEFAULT '',
[Branch Zip] varchar(20) DEFAULT '',
[Survey Letter Signature Name] varchar(75) DEFAULT '',
[Survey Letter Signature Title] varchar(75) DEFAULT '',
[Call Person] varchar(50) DEFAULT '',
[Call Person Phone] varchar(50) DEFAULT '',
[Survey Language] varchar(50) DEFAULT '',
[CreateDateTime] [datetime] DEFAULT GETDATE()
) ON DIMGROUP