DROP TABLE Member
GO
CREATE TABLE [Member](
	[member_key] [int] IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[create_datetime] [datetime] DEFAULT GETDATE(),
	[change_datetime] [datetime] DEFAULT GETDATE(),
	[next_change_datetime] [datetime] DEFAULT DATEADD(YY, 100, GETDATE()),
	[current_indicator] [bit] DEFAULT 1,
	[member_cleansed_id] [varchar](50) DEFAULT '',
	[organization_name] [varchar](50) DEFAULT '',
	[organization_id] [varchar](20) DEFAULT '',
	[member_id] [varchar](50) DEFAULT '',
	[family_id] [varchar](50) DEFAULT '',
	[number_in_household] [varchar](10) DEFAULT '',
	[head_of_household] [varchar](1) DEFAULT '',
	[member_first_name] [varchar](50) DEFAULT '',
	[member_middle_name] [varchar](50) DEFAULT '',
	[member_last_name] [varchar](50) DEFAULT '',
	[member_name_suffix] [varchar](10) DEFAULT '',
	[address_1] [varchar](100) DEFAULT '',
	[address_2] [varchar](100) DEFAULT '',
	[address_city] [varchar](100) DEFAULT '',
	[address_state] [varchar](25) DEFAULT '',
	[address_postal] [varchar](25) DEFAULT '',
	[address_country] [varchar](25) DEFAULT '',
	[parsed_address_1] [varchar](100) DEFAULT '',
	[parsed_address_2] [varchar](100) DEFAULT '',
	[parsed_address_city] [varchar](100) DEFAULT '',
	[parsed_address_state] [varchar](25) DEFAULT '',
	[parsed_address_postal] [varchar](25) DEFAULT '',
	[parsed_address_country] [varchar](25) DEFAULT '',
	[parsed_address_line_quality] [varchar](20) DEFAULT '',
	[parsed_address_csz_quality] [varchar](20) DEFAULT '',
	[home_phone] [varchar](50) DEFAULT '',
	[gender] [varchar](1) DEFAULT '',
	[ethnicity] [varchar](50) DEFAULT '',
	[birth_date] [varchar](25) DEFAULT 'JAN 01 1900',
	[membership_date] date DEFAULT 'JAN 01 1900',
	[category] [varchar](75) DEFAULT '',
	[membership_type] [varchar](75) DEFAULT '',
	[staff_type] [varchar](75) DEFAULT '',
	[full_time_part_time] [varchar](50) DEFAULT '',
	[hourly_salary] [varchar](25) DEFAULT '',
	[is_primary_member] [varchar](1) DEFAULT '',
	[is_employee] [varchar](1) DEFAULT '',
	[is_donor] [varchar](1) DEFAULT '',
	[is_program_member] [varchar](1) DEFAULT '',
	[is_new_member] [varchar](1) DEFAULT '',
	[is_health_seeker] [varchar](1) DEFAULT '',
	[is_active] [varchar](1) DEFAULT '',
	[removal_reason] [varchar](100) DEFAULT '',
	[comments] [varchar](255) DEFAULT '',
	[record_type] [varchar](75) DEFAULT '',
	[mailable_member] [varchar](1) DEFAULT '',
	[emailable_member] [varchar](1) DEFAULT '',
	[mailable_employee] [varchar](1) DEFAULT '',
	[emailable_employee] [varchar](1) DEFAULT '',
	[emailable_new_member] [varchar](1) DEFAULT '',
	[emailable_program_member] [varchar](1) DEFAULT '',
	[program_site_location] [varchar](100) DEFAULT '',
	[phone] [varchar](20) DEFAULT '',
	[email_address] [varchar](100) DEFAULT '',
	[exact_age] [varchar](5) DEFAULT '',
	[estimated_age] tinyint DEFAULT 0,
	[estimated_household_income_amount] [varchar](1) DEFAULT 0,
	[county_income_percentile] decimal (20, 5) DEFAULT 0,
	[marital_status] [varchar](5) DEFAULT '',
	[filler_01] [varchar](1) DEFAULT '',
	[filler_02] [varchar](1) DEFAULT '',
	[filler_03] [varchar](1) DEFAULT '',
	[filler_04] [varchar](1) DEFAULT '',
	[filler_05] [varchar](1) DEFAULT '',
	[filler_06] [varchar](1) DEFAULT '',
	[filler_07] [varchar](1) DEFAULT '',
	[filler_08] [varchar](1) DEFAULT '',
	[filler_09] [varchar](1) DEFAULT '',
	[home_business_indicator] [varchar](1) DEFAULT '',
	[presence_of_children_03] [varchar](1) DEFAULT '',
	[gender_of_children_03] [varchar](1) DEFAULT '',
	[presence_of_children_46] [varchar](1) DEFAULT '',
	[gender_of_children_46] [varchar](1) DEFAULT '',
	[presence_of_children_79] [varchar](1) DEFAULT '',
	[gender_of_children_79] [varchar](1) DEFAULT '',
	[presence_of_children_1012] [varchar](1) DEFAULT '',
	[gender_of_children_1012] [varchar](1) DEFAULT '',
	[presence_of_children_1318] [varchar](1) DEFAULT '',
	[gender_of_children_1318] [varchar](1) DEFAULT '',
	[number_of_adults_in_household] tinyint,
	[home_owner] [varchar](1) DEFAULT '',
	[probable_home_owner] [varchar](1) DEFAULT '',
	[length_of_residence] [varchar](1000) DEFAULT '',
	[dwelling_unit_size_code] [varchar](1) DEFAULT '',
	[year_built] smallint DEFAULT 0,
	[multi_codirect_mail] [varchar](1) DEFAULT '',
	[news_and_financial] [varchar](10) DEFAULT '',
	[current_estimated_median_family_income] money,
	[median_education_years_attained] tinyint DEFAULT 0,
	[pct_occ_management] decimal (20, 5) DEFAULT 0,
	[pct_occ_health_technologists] decimal (20, 5) DEFAULT 0,
	[pct_white_only] decimal (20, 5) DEFAULT 0,
	[median_housing_value] money DEFAULT 0,
	[pct_population_under_4] decimal (20, 5) DEFAULT 0,
	[pct_population_59] decimal (20, 5) DEFAULT 0,
	[pct_population_1013] decimal (20, 5) DEFAULT 0,
	[pct_population_1417] decimal (20, 5) DEFAULT 0,
	[pct_dwelling_owner_occupied] decimal (20, 5) DEFAULT 0,
	[pct_dwelling_renter_occupied] decimal (20, 5) DEFAULT 0,
	[current_estimated_family_income_decile] decimal (20, 5) DEFAULT 0,
	[bible_devotional_religious] [varchar](1) DEFAULT '',
	[volunteer_work] [varchar](1) DEFAULT '',
	[hoh_education_flag] [varchar](5) DEFAULT '',
	[hoh_occupation_flag] [varchar](5) DEFAULT '',
	[animal_welfare_contributions] [varchar](1) DEFAULT '',
	[childrens_welfare] [varchar](1) DEFAULT '',
	[cultural_welfare] [varchar](1) DEFAULT '',
	[environmental] [varchar](1) DEFAULT '',
	[health_related] [varchar](1) DEFAULT '',
	[political] [varchar](1) DEFAULT '',
	[religious_contributions] [varchar](1) DEFAULT '',
	[social_services] [varchar](1) DEFAULT '',
	[use_mac_computer] [varchar](1) DEFAULT '',
	[own_cd_rom] [varchar](1) DEFAULT '',
	[use_modem] [varchar](1) DEFAULT '',
	[own_computer] [varchar](1) DEFAULT '',
	[laser_printer] [varchar](1) DEFAULT '',
	[color_printer] [varchar](1) DEFAULT '',
	[use_internet_service] [varchar](1) DEFAULT '',
	[stock_bond_investor] [varchar](1) DEFAULT '',
	[cd_money_market_investor] [varchar](1) DEFAULT '',
	[ira_investor] [varchar](1) DEFAULT '',
	[mutual_fund_investor] [varchar](1) DEFAULT '',
	[real_estate_investor] [varchar](1) DEFAULT '',
	[crafts] [varchar](1) DEFAULT '',
	[estimated_current_home_value] money DEFAULT 0,
	[latitude] [varchar](10) DEFAULT '',
	[longitude] [varchar](10) DEFAULT '',
	[lev_lat_long] [varchar](1) DEFAULT '',
	[fips_state_code] [varchar](75) DEFAULT '',
	[fips_county_code] [varchar](75) DEFAULT '',
	[census_tract] [varchar](25) DEFAULT '',
	[census_block_group] [varchar](25) DEFAULT '',
	[block_id] [varchar](25) DEFAULT '',
	[mcdccd_code] [varchar](75) DEFAULT '',
	[cbsa_code] [varchar](75) DEFAULT '',
	[enhancement_match_type] [varchar](1) DEFAULT '',
	[census_match_level] [varchar](1) DEFAULT '',
	[current_estimated_family_income_amount] money DEFAULT 0,
	[current_estimated_family_income_code] [varchar](75) DEFAULT ''
) ON TRXGROUP

GO




