drop table Survey_Segment
go
CREATE TABLE Survey_Segment([survey_segment_key] [int] identity(1, 1) not null PRIMARY KEY,
							[member_key] [bigint],
							[organization_key] [int],
							[survey_form_key] [int],
							[create_datetime] [datetime] DEFAULT GETDATE(),
							[change_datetime] [datetime] DEFAULT GETDATE(),
							[next_change_datetime] [datetime] DEFAULT DATEADD(YY, 100, GETDATE()),
							[current_indicator] [bit] DEFAULT 1,
							[membership_type] [varchar](50),
							[loyalty] [varchar](50),
							[intent_to_renew] [varchar](50),
							[frequency_of_use] [varchar](50),
							[length_of_membership] [varchar](50),
							[time_of_day] [varchar](50),
							[net_promoter] [varchar](50),
							[health_seeker] [varchar](50),
							[health_seeker_fitness_goals] [varchar](50),
							[employee_type] [varchar](50),
							[employee_work_time] [varchar](50),
							[employee_length_of_service] [varchar](50),
							[employee_department] [varchar](50),
							[employee_promoter] [varchar](50),
							[employee_membership_promoter] [varchar](50),
							[group_activities] [varchar](50),
							[program_promoter] [varchar](50)	
							) ON DIMGROUP;