/*
drop procedure spPopulate_mdmMember
truncate table Seer_MDM.dbo.Member
truncate table Seer_CTRL.dbo.Member
*/
CREATE PROCEDURE spPopulate_mdmMember AS
BEGIN
	MERGE	Seer_MDM.dbo.Member AS target
	USING	(
			SELECT	distinct
					A.Member_Key member_key,
					A.[MemberCleansedID] member_cleansed_id,
					A.[OrganizationName] organization_name,
					A.[OrganizationId] organization_id,
					A.[MemberId] member_id,
					A.[FamilyId] family_id,
					A.[NumberInHousehold] number_in_household,
					A.[HeadOfHousehold] head_of_household,
					A.[MemberFirstName] member_first_name,
					A.[MemberMiddleName] member_middle_name,
					A.[MemberLastName] member_last_name,
					A.[MemberNameSuffix] member_name_suffix,
					A.[Address1] address_1,
					A.[Address2] address_2,
					A.[AddressCity] address_city,
					A.[AddressState] address_state,
					A.[AddressPostal] address_postal,
					A.[AddressCountry] address_country,
					A.[ParsedAddress1] parsed_address_1,
					A.[ParsedAddress2] parsed_address_2,
					A.[ParsedAddressCity] parsed_address_city,
					A.[ParsedAddressState] parsed_address_state,
					A.[ParsedAddressPostal] parsed_address_postal,
					A.[ParsedAddressCountry] parsed_address_country,
					A.[ParsedAddressLineQuality] parsed_address_line_quality,
					A.[ParsedAddressCSZQuality] parsed_address_csz_quality,
					A.[HomePhone] home_phone,
					A.[Gender] gender,
					A.[Ethnicity] ethnicity,
					A.[Birthdate] birth_date,
					A.[MembershipDate] membership_date,
					A.[Category] category,
					A.[MembershipType] membership_type,
					A.[StaffType] staff_type,
					A.[FullTimePartTime] full_time_part_time,
					A.[HourlySalary] hourly_salary,
					A.[IsPrimaryMember] is_primary_member,
					A.[IsEmployee] is_employee,
					A.[IsDonor] is_donor,
					A.[IsProgramMember] is_program_member,
					A.[IsNewMember] is_new_member,
					CASE WHEN (COALESCE(B.Q_27, C.Q_27) = '1' and COALESCE(B.Q_28, C.Q_28) = '1') THEN 'Y'
						ELSE 'N'
					END AS is_health_seeker,
					A.[IsActive] is_active,
					A.[RemovalReason] removal_reason,
					A.[Comments] comments,
					A.[RecordType] record_type,
					A.[MailableMember] mailable_member,
					A.[EmailableMember] emailable_member,
					A.[MailableEmployee] mailable_employee,
					A.[EmailableEmployee] emailable_employee,
					A.[EmailableNewMember] emailable_new_member,
					A.[EmailableProgramMember] emailable_program_member,
					A.[ProgramSiteLocation] program_site_location,
					A.[Phone] phone,
					A.[EmailAddress] email_address,
					A.[ExactAge] exact_age,
					A.[EstimatedAge] estimated_age,
					A.[EstimatedHouseholdIncomeAmount] estimated_household_income_amount,
					A.[CountyIncomePercentile] county_income_percentile,
					A.[MaritalStatus] marital_status,
					A.[Filler01] filler_01,
					A.[Filler02] filler_02,
					A.[Filler03] filler_03,
					A.[Filler04] filler_04,
					A.[Filler05] filler_05,
					A.[Filler06] filler_06,
					A.[Filler07] filler_07,
					A.[Filler08] filler_08,
					A.[Filler09] filler_09,
					A.[HomeBusinessIndicator] home_business_indicator,
					A.[PresenceOfChildren03] presence_of_children_03,
					A.[GenderOfChildren03] gender_of_children_03,
					A.[PresenceOfChildren46] presence_of_children_46,
					A.[GenderOfChildren46] gender_of_children_46,
					A.[PresenceOfChildren79] presence_of_children_79,
					A.[GenderOfChildren79] gender_of_children_79,
					A.[PresenceOfChildren1012] presence_of_children_1012,
					A.[GenderOfChildren1012] gender_of_children_1012,
					A.[PresenceOfChildren1318] presence_of_children_1318,
					A.[GenderOfChildren1318] gender_of_children_1318,
					A.[NumberOfAdultsInHousehold] number_of_adults_in_household,
					A.[Homeowner] home_owner,
					A.[ProbableHomeowner] probable_home_owner,
					A.[LengthOfResidence] length_of_residence,
					A.[DwellingUnitSizeCode] dwelling_unit_size_code,
					A.[YearBuilt] year_built,
					A.[MultiCoDirectMail] multi_codirect_mail,
					A.[NewsAndFinancial] news_and_financial,
					A.[CurrentEstimatedMedianFamilyIncome] current_estimated_median_family_income,
					A.[MedianEducationYearsAttained] median_education_years_attained,
					A.[PctOccManagement] pct_occ_management,
					A.[PctOccHealthTechnologists] pct_occ_health_technologists,
					A.[PctWhiteOnly] pct_white_only,
					A.[MedianHousingValue] median_housing_value,
					A.[PctPopulationUnder4] pct_population_under_4,
					A.[PctPopulation59] pct_population_59,
					A.[PctPopulation1013] pct_population_1013,
					A.[PctPopulation1417] pct_population_1417,
					A.[PctDwellingOwnerOccupied] pct_dwelling_owner_occupied,
					A.[PctDwellingRenterOccupied] pct_dwelling_renter_occupied,
					A.[CurrentEstimatedFamilyIncomeDecile] current_estimated_family_income_decile,
					A.[BibleDevotionalReligious] bible_devotional_religious,
					A.[VolunteerWork] volunteer_work,
					A.[HOHEducationFlag] hoh_education_flag,
					A.[HOHOccupationFlag] hoh_occupation_flag,
					A.[AnimalWelfareContributions] animal_welfare_contributions,
					A.[ChildrensWelfare] childrens_welfare,
					A.[CulturalWelfare] cultural_welfare,
					A.[Environmental] environmental,
					A.[HealthRelated] health_related,
					A.[Political] political,
					A.[ReligiousContributions] religious_contributions,
					A.[SocialServices] social_services,
					A.[UseMacComputer] use_mac_computer,
					A.[OwnCDRom] own_cd_rom,
					A.[UseModem] use_modem,
					A.[OwnComputer] own_computer,
					A.[LaserPrinter] laser_printer,
					A.[ColorPrinter] color_printer,
					A.[UseInternetService] use_internet_service,
					A.[StockBondInvestor] stock_bond_investor,
					A.[CDMoneyMarketInvestor] cd_money_market_investor,
					A.[IRAInvestor] ira_investor,
					A.[MutualFundInvestor] mutual_fund_investor,
					A.[RealEstateInvestor] real_estate_investor,
					A.[Crafts] crafts,
					A.[EstimatedCurrentHomeValue] estimated_current_home_value,
					A.[Latitude] latitude,
					A.[Longitude] longitude,
					A.[LevLatLong] lev_lat_long,
					A.[FipsStateCode] fips_state_code,
					A.[FipsCountyCode] fips_county_code,
					A.[CensusTract] census_tract,
					A.[CensusBlockGroup] census_block_group,
					A.[BlockId] block_id,
					A.[MCDCCDCode] mcdccd_code,
					A.[CBSACode] cbsa_code,
					A.[EnhancementMatchType] enhancement_match_type,
					A.[CensusMatchLevel] census_match_level,
					A.[CurrentEstimatedFamilyIncomeAmount] current_estimated_family_income_amount,
					A.[CurrentEstimatedFamilyIncomeCode] current_estimated_family_income_code
			
			FROM	Seer_STG.dbo.Member A
					LEFT JOIN Seer_STG.dbo.[Member Response Data] B
						ON A.Member_Key = B.Member_Key
					LEFT JOIN Seer_STG.dbo.[Member Response Data] C
						ON A.Seer_Key = C.SeerKey
			
			WHERE	ISDATE(COALESCE(MembershipDate, 'JAN 01 1900')) = 1
			) AS source
			ON target.organization_id = source.organization_id
					AND target.member_id = source.member_id
					AND target.member_first_name = source.member_first_name
					AND target.member_middle_name = source.member_middle_name
					AND target.member_last_name = source.member_last_name
					AND target.email_address = source.email_address
			
	WHEN MATCHED AND (target.member_key	 <> 	source.member_key
						OR target.member_cleansed_id	 <> 	source.member_cleansed_id
						OR target.organization_name	 <> 	source.organization_name
						OR target.family_id	 <> 	source.family_id
						OR target.number_in_household	 <> 	source.number_in_household
						OR target.head_of_household	 <> 	source.head_of_household
						OR target.member_name_suffix	 <> 	source.member_name_suffix
						OR target.address_1	 <> 	source.address_1
						OR target.address_2	 <> 	source.address_2
						OR target.address_city	 <> 	source.address_city
						OR target.address_state	 <> 	source.address_state
						OR target.address_postal	 <> 	source.address_postal
						OR target.address_country	 <> 	source.address_country
						OR target.parsed_address_1	 <> 	source.parsed_address_1
						OR target.parsed_address_2	 <> 	source.parsed_address_2
						OR target.parsed_address_city	 <> 	source.parsed_address_city
						OR target.parsed_address_state	 <> 	source.parsed_address_state
						OR target.parsed_address_postal	 <> 	source.parsed_address_postal
						OR target.parsed_address_country	 <> 	source.parsed_address_country
						OR target.parsed_address_line_quality	 <> 	source.parsed_address_line_quality
						OR target.parsed_address_csz_quality	 <> 	source.parsed_address_csz_quality
						OR target.home_phone	 <> 	source.home_phone
						OR target.gender	 <> 	source.gender
						OR target.ethnicity	 <> 	source.ethnicity
						OR target.birth_date	 <> 	source.birth_date
						OR target.membership_date	 <> 	source.membership_date
						OR target.category	 <> 	source.category
						OR target.membership_type	 <> 	source.membership_type
						OR target.staff_type	 <> 	source.staff_type
						OR target.full_time_part_time	 <> 	source.full_time_part_time
						OR target.hourly_salary	 <> 	source.hourly_salary
						OR target.is_primary_member	 <> 	source.is_primary_member
						OR target.is_employee	 <> 	source.is_employee
						OR target.is_donor	 <> 	source.is_donor
						OR target.is_program_member	 <> 	source.is_program_member
						OR target.is_new_member	 <> 	source.is_new_member
						OR target.is_active	 <> 	source.is_active
						OR target.removal_reason	 <> 	source.removal_reason
						OR target.comments	 <> 	source.comments
						OR target.record_type	 <> 	source.record_type
						OR target.mailable_member	 <> 	source.mailable_member
						OR target.emailable_member	 <> 	source.emailable_member
						OR target.mailable_employee	 <> 	source.mailable_employee
						OR target.emailable_employee	 <> 	source.emailable_employee
						OR target.emailable_new_member	 <> 	source.emailable_new_member
						OR target.emailable_program_member	 <> 	source.emailable_program_member
						OR target.program_site_location <> source.program_site_location
						OR target.phone	 <> 	source.phone
						OR target.exact_age	 <> 	source.exact_age
						OR target.estimated_age	 <> 	source.estimated_age
						OR target.estimated_household_income_amount	 <> 	source.estimated_household_income_amount
						OR target.county_income_percentile	 <> 	source.county_income_percentile
						OR target.marital_status	 <> 	source.marital_status
						OR target.filler_01	 <> 	source.filler_01
						OR target.filler_02	 <> 	source.filler_02
						OR target.filler_03	 <> 	source.filler_03
						OR target.filler_04	 <> 	source.filler_04
						OR target.filler_05	 <> 	source.filler_05
						OR target.filler_06	 <> 	source.filler_06
						OR target.filler_07	 <> 	source.filler_07
						OR target.filler_08	 <> 	source.filler_08
						OR target.filler_09	 <> 	source.filler_09
						OR target.home_business_indicator	 <> 	source.home_business_indicator
						OR target.presence_of_children_03	 <> 	source.presence_of_children_03
						OR target.gender_of_children_03	 <> 	source.gender_of_children_03
						OR target.presence_of_children_46	 <> 	source.presence_of_children_46
						OR target.gender_of_children_46	 <> 	source.gender_of_children_46
						OR target.presence_of_children_79	 <> 	source.presence_of_children_79
						OR target.gender_of_children_79	 <> 	source.gender_of_children_79
						OR target.presence_of_children_1012	 <> 	source.presence_of_children_1012
						OR target.gender_of_children_1012	 <> 	source.gender_of_children_1012
						OR target.presence_of_children_1318	 <> 	source.presence_of_children_1318
						OR target.gender_of_children_1318	 <> 	source.gender_of_children_1318
						OR target.number_of_adults_in_household	 <> 	source.number_of_adults_in_household
						OR target.home_owner	 <> 	source.home_owner
						OR target.probable_home_owner	 <> 	source.probable_home_owner
						OR target.length_of_residence	 <> 	source.length_of_residence
						OR target.dwelling_unit_size_code	 <> 	source.dwelling_unit_size_code
						OR target.year_built	 <> 	source.year_built
						OR target.multi_codirect_mail	 <> 	source.multi_codirect_mail
						OR target.news_and_financial	 <> 	source.news_and_financial
						OR target.current_estimated_median_family_income	 <> 	source.current_estimated_median_family_income
						OR target.median_education_years_attained	 <> 	source.median_education_years_attained
						OR target.pct_occ_management	 <> 	source.pct_occ_management
						OR target.pct_occ_health_technologists	 <> 	source.pct_occ_health_technologists
						OR target.pct_white_only	 <> 	source.pct_white_only
						OR target.median_housing_value	 <> 	source.median_housing_value
						OR target.pct_population_under_4	 <> 	source.pct_population_under_4
						OR target.pct_population_59	 <> 	source.pct_population_59
						OR target.pct_population_1013	 <> 	source.pct_population_1013
						OR target.pct_population_1417	 <> 	source.pct_population_1417
						OR target.pct_dwelling_owner_occupied	 <> 	source.pct_dwelling_owner_occupied
						OR target.pct_dwelling_renter_occupied	 <> 	source.pct_dwelling_renter_occupied
						OR target.current_estimated_family_income_decile	 <> 	source.current_estimated_family_income_decile
						OR target.bible_devotional_religious	 <> 	source.bible_devotional_religious
						OR target.volunteer_work	 <> 	source.volunteer_work
						OR target.hoh_education_flag	 <> 	source.hoh_education_flag
						OR target.hoh_occupation_flag	 <> 	source.hoh_occupation_flag
						OR target.animal_welfare_contributions	 <> 	source.animal_welfare_contributions
						OR target.childrens_welfare	 <> 	source.childrens_welfare
						OR target.cultural_welfare	 <> 	source.cultural_welfare
						OR target.environmental	 <> 	source.environmental
						OR target.health_related	 <> 	source.health_related
						OR target.political	 <> 	source.political
						OR target.religious_contributions	 <> 	source.religious_contributions
						OR target.social_services	 <> 	source.social_services
						OR target.use_mac_computer	 <> 	source.use_mac_computer
						OR target.own_cd_rom	 <> 	source.own_cd_rom
						OR target.use_modem	 <> 	source.use_modem
						OR target.own_computer	 <> 	source.own_computer
						OR target.laser_printer	 <> 	source.laser_printer
						OR target.color_printer	 <> 	source.color_printer
						OR target.use_internet_service	 <> 	source.use_internet_service
						OR target.stock_bond_investor	 <> 	source.stock_bond_investor
						OR target.cd_money_market_investor	 <> 	source.cd_money_market_investor
						OR target.ira_investor	 <> 	source.ira_investor
						OR target.mutual_fund_investor	 <> 	source.mutual_fund_investor
						OR target.real_estate_investor	 <> 	source.real_estate_investor
						OR target.crafts	 <> 	source.crafts
						OR target.estimated_current_home_value	 <> 	source.estimated_current_home_value
						OR target.latitude	 <> 	source.latitude
						OR target.longitude	 <> 	source.longitude
						OR target.lev_lat_long	 <> 	source.lev_lat_long
						OR target.fips_state_code	 <> 	source.fips_state_code
						OR target.fips_county_code	 <> 	source.fips_county_code
						OR target.census_tract	 <> 	source.census_tract
						OR target.census_block_group	 <> 	source.census_block_group
						OR target.block_id	 <> 	source.block_id
						OR target.mcdccd_code	 <> 	source.mcdccd_code
						OR target.cbsa_code	 <> 	source.cbsa_code
						OR target.enhancement_match_type	 <> 	source.enhancement_match_type
						OR target.census_match_level	 <> 	source.census_match_level
						OR target.current_estimated_family_income_amount	 <> 	source.current_estimated_family_income_amount
						OR target.current_estimated_family_income_code	 <> 	source.current_estimated_family_income_code
						)
		THEN
			UPDATE	
			SET		member_cleansed_id	 = 	source.member_cleansed_id,
					organization_name	 = 	source.organization_name,
					family_id	 = 	source.family_id,
					number_in_household	 = 	source.number_in_household,
					head_of_household	 = 	source.head_of_household,
					member_name_suffix	 = 	source.member_name_suffix,
					address_1	 = 	source.address_1,
					address_2	 = 	source.address_2,
					address_city	 = 	source.address_city,
					address_state	 = 	source.address_state,
					address_postal	 = 	source.address_postal,
					address_country	 = 	source.address_country,
					parsed_address_1	 = 	source.parsed_address_1,
					parsed_address_2	 = 	source.parsed_address_2,
					parsed_address_city	 = 	source.parsed_address_city,
					parsed_address_state	 = 	source.parsed_address_state,
					parsed_address_postal	 = 	source.parsed_address_postal,
					parsed_address_country	 = 	source.parsed_address_country,
					parsed_address_line_quality	 = 	source.parsed_address_line_quality,
					parsed_address_csz_quality	 = 	source.parsed_address_csz_quality,
					home_phone	 = 	source.home_phone,
					gender	 = 	source.gender,
					ethnicity	 = 	source.ethnicity,
					birth_date	 = 	source.birth_date,
					membership_date	 = 	source.membership_date,
					category	 = 	source.category,
					membership_type	 = 	source.membership_type,
					staff_type	 = 	source.staff_type,
					full_time_part_time	 = 	source.full_time_part_time,
					hourly_salary	 = 	source.hourly_salary,
					is_primary_member	 = 	source.is_primary_member,
					is_employee	 = 	source.is_employee,
					is_donor	 = 	source.is_donor,
					is_program_member	 = 	source.is_program_member,
					is_new_member	 = 	source.is_new_member,
					is_health_seeker = source.is_health_seeker,
					is_active	 = 	source.is_active,
					removal_reason	 = 	source.removal_reason,
					comments	 = 	source.comments,
					record_type	 = 	source.record_type,
					mailable_member	 = 	source.mailable_member,
					emailable_member	 = 	source.emailable_member,
					mailable_employee	 = 	source.mailable_employee,
					emailable_employee	 = 	source.emailable_employee,
					emailable_new_member	 = 	source.emailable_new_member,
					emailable_program_member	 = 	source.emailable_program_member,
					program_site_location = source.program_site_location,
					phone	 = 	source.phone,
					exact_age	 = 	source.exact_age,
					estimated_age	 = 	source.estimated_age,
					estimated_household_income_amount	 = 	source.estimated_household_income_amount,
					county_income_percentile	 = 	source.county_income_percentile,
					marital_status	 = 	source.marital_status,
					filler_01	 = 	source.filler_01,
					filler_02	 = 	source.filler_02,
					filler_03	 = 	source.filler_03,
					filler_04	 = 	source.filler_04,
					filler_05	 = 	source.filler_05,
					filler_06	 = 	source.filler_06,
					filler_07	 = 	source.filler_07,
					filler_08	 = 	source.filler_08,
					filler_09	 = 	source.filler_09,
					home_business_indicator	 = 	source.home_business_indicator,
					presence_of_children_03	 = 	source.presence_of_children_03,
					gender_of_children_03	 = 	source.gender_of_children_03,
					presence_of_children_46	 = 	source.presence_of_children_46,
					gender_of_children_46	 = 	source.gender_of_children_46,
					presence_of_children_79	 = 	source.presence_of_children_79,
					gender_of_children_79	 = 	source.gender_of_children_79,
					presence_of_children_1012	 = 	source.presence_of_children_1012,
					gender_of_children_1012	 = 	source.gender_of_children_1012,
					presence_of_children_1318	 = 	source.presence_of_children_1318,
					gender_of_children_1318	 = 	source.gender_of_children_1318,
					number_of_adults_in_household	 = 	source.number_of_adults_in_household,
					home_owner	 = 	source.home_owner,
					probable_home_owner	 = 	source.probable_home_owner,
					length_of_residence	 = 	source.length_of_residence,
					dwelling_unit_size_code	 = 	source.dwelling_unit_size_code,
					year_built	 = 	source.year_built,
					multi_codirect_mail	 = 	source.multi_codirect_mail,
					news_and_financial	 = 	source.news_and_financial,
					current_estimated_median_family_income	 = 	source.current_estimated_median_family_income,
					median_education_years_attained	 = 	source.median_education_years_attained,
					pct_occ_management	 = 	source.pct_occ_management,
					pct_occ_health_technologists	 = 	source.pct_occ_health_technologists,
					pct_white_only	 = 	source.pct_white_only,
					median_housing_value	 = 	source.median_housing_value,
					pct_population_under_4	 = 	source.pct_population_under_4,
					pct_population_59	 = 	source.pct_population_59,
					pct_population_1013	 = 	source.pct_population_1013,
					pct_population_1417	 = 	source.pct_population_1417,
					pct_dwelling_owner_occupied	 = 	source.pct_dwelling_owner_occupied,
					pct_dwelling_renter_occupied	 = 	source.pct_dwelling_renter_occupied,
					current_estimated_family_income_decile	 = 	source.current_estimated_family_income_decile,
					bible_devotional_religious	 = 	source.bible_devotional_religious,
					volunteer_work	 = 	source.volunteer_work,
					hoh_education_flag	 = 	source.hoh_education_flag,
					hoh_occupation_flag	 = 	source.hoh_occupation_flag,
					animal_welfare_contributions	 = 	source.animal_welfare_contributions,
					childrens_welfare	 = 	source.childrens_welfare,
					cultural_welfare	 = 	source.cultural_welfare,
					environmental	 = 	source.environmental,
					health_related	 = 	source.health_related,
					political	 = 	source.political,
					religious_contributions	 = 	source.religious_contributions,
					social_services	 = 	source.social_services,
					use_mac_computer	 = 	source.use_mac_computer,
					own_cd_rom	 = 	source.own_cd_rom,
					use_modem	 = 	source.use_modem,
					own_computer	 = 	source.own_computer,
					laser_printer	 = 	source.laser_printer,
					color_printer	 = 	source.color_printer,
					use_internet_service	 = 	source.use_internet_service,
					stock_bond_investor	 = 	source.stock_bond_investor,
					cd_money_market_investor	 = 	source.cd_money_market_investor,
					ira_investor	 = 	source.ira_investor,
					mutual_fund_investor	 = 	source.mutual_fund_investor,
					real_estate_investor	 = 	source.real_estate_investor,
					crafts	 = 	source.crafts,
					estimated_current_home_value	 = 	source.estimated_current_home_value,
					latitude	 = 	source.latitude,
					longitude	 = 	source.longitude,
					lev_lat_long	 = 	source.lev_lat_long,
					fips_state_code	 = 	source.fips_state_code,
					fips_county_code	 = 	source.fips_county_code,
					census_tract	 = 	source.census_tract,
					census_block_group	 = 	source.census_block_group,
					block_id	 = 	source.block_id,
					mcdccd_code	 = 	source.mcdccd_code,
					cbsa_code	 = 	source.cbsa_code,
					enhancement_match_type	 = 	source.enhancement_match_type,
					census_match_level	 = 	source.census_match_level,
					current_estimated_family_income_amount	 = 	source.current_estimated_family_income_amount,
					current_estimated_family_income_code	 = 	source.current_estimated_family_income_code


						
	WHEN NOT MATCHED BY target AND
		(ISDATE(COALESCE(source.membership_date, 'JAN 01 1900')) = 1
		)
		THEN 
			INSERT (member_cleansed_id,
					organization_name,
					organization_id,
					member_id,
					family_id,
					number_in_household,
					head_of_household,
					member_first_name,
					member_middle_name,
					member_last_name,
					member_name_suffix,
					address_1,
					address_2,
					address_city,
					address_state,
					address_postal,
					address_country,
					parsed_address_1,
					parsed_address_2,
					parsed_address_city,
					parsed_address_state,
					parsed_address_postal,
					parsed_address_country,
					parsed_address_line_quality,
					parsed_address_csz_quality,
					home_phone,
					gender,
					ethnicity,
					birth_date,
					membership_date,
					category,
					membership_type,
					staff_type,
					full_time_part_time,
					hourly_salary,
					is_primary_member,
					is_employee,
					is_donor,
					is_program_member,
					is_new_member,
					is_health_seeker,
					is_active,
					removal_reason,
					comments,
					record_type,
					mailable_member,
					emailable_member,
					mailable_employee,
					emailable_employee,
					emailable_new_member,
					emailable_program_member,
					program_site_location,
					phone,
					email_address,
					exact_age,
					estimated_age,
					estimated_household_income_amount,
					county_income_percentile,
					marital_status,
					filler_01,
					filler_02,
					filler_03,
					filler_04,
					filler_05,
					filler_06,
					filler_07,
					filler_08,
					filler_09,
					home_business_indicator,
					presence_of_children_03,
					gender_of_children_03,
					presence_of_children_46,
					gender_of_children_46,
					presence_of_children_79,
					gender_of_children_79,
					presence_of_children_1012,
					gender_of_children_1012,
					presence_of_children_1318,
					gender_of_children_1318,
					number_of_adults_in_household,
					home_owner,
					probable_home_owner,
					length_of_residence,
					dwelling_unit_size_code,
					year_built,
					multi_codirect_mail,
					news_and_financial,
					current_estimated_median_family_income,
					median_education_years_attained,
					pct_occ_management,
					pct_occ_health_technologists,
					pct_white_only,
					median_housing_value,
					pct_population_under_4,
					pct_population_59,
					pct_population_1013,
					pct_population_1417,
					pct_dwelling_owner_occupied,
					pct_dwelling_renter_occupied,
					current_estimated_family_income_decile,
					bible_devotional_religious,
					volunteer_work,
					hoh_education_flag,
					hoh_occupation_flag,
					animal_welfare_contributions,
					childrens_welfare,
					cultural_welfare,
					environmental,
					health_related,
					political,
					religious_contributions,
					social_services,
					use_mac_computer,
					own_cd_rom,
					use_modem,
					own_computer,
					laser_printer,
					color_printer,
					use_internet_service,
					stock_bond_investor,
					cd_money_market_investor,
					ira_investor,
					mutual_fund_investor,
					real_estate_investor,
					crafts,
					estimated_current_home_value,
					latitude,
					longitude,
					lev_lat_long,
					fips_state_code,
					fips_county_code,
					census_tract,
					census_block_group,
					block_id,
					mcdccd_code,
					cbsa_code,
					enhancement_match_type,
					census_match_level,
					current_estimated_family_income_amount,
					current_estimated_family_income_code
)
			VALUES (member_cleansed_id,
					organization_name,
					organization_id,
					member_id,
					family_id,
					number_in_household,
					head_of_household,
					member_first_name,
					member_middle_name,
					member_last_name,
					member_name_suffix,
					address_1,
					address_2,
					address_city,
					address_state,
					address_postal,
					address_country,
					parsed_address_1,
					parsed_address_2,
					parsed_address_city,
					parsed_address_state,
					parsed_address_postal,
					parsed_address_country,
					parsed_address_line_quality,
					parsed_address_csz_quality,
					home_phone,
					gender,
					ethnicity,
					birth_date,
					membership_date,
					category,
					membership_type,
					staff_type,
					full_time_part_time,
					hourly_salary,
					is_primary_member,
					is_employee,
					is_donor,
					is_program_member,
					is_new_member,
					is_health_seeker,
					is_active,
					removal_reason,
					comments,
					record_type,
					mailable_member,
					emailable_member,
					mailable_employee,
					emailable_employee,
					emailable_new_member,
					emailable_program_member,
					program_site_location,
					phone,
					email_address,
					exact_age,
					estimated_age,
					estimated_household_income_amount,
					county_income_percentile,
					marital_status,
					filler_01,
					filler_02,
					filler_03,
					filler_04,
					filler_05,
					filler_06,
					filler_07,
					filler_08,
					filler_09,
					home_business_indicator,
					presence_of_children_03,
					gender_of_children_03,
					presence_of_children_46,
					gender_of_children_46,
					presence_of_children_79,
					gender_of_children_79,
					presence_of_children_1012,
					gender_of_children_1012,
					presence_of_children_1318,
					gender_of_children_1318,
					number_of_adults_in_household,
					home_owner,
					probable_home_owner,
					length_of_residence,
					dwelling_unit_size_code,
					year_built,
					multi_codirect_mail,
					news_and_financial,
					current_estimated_median_family_income,
					median_education_years_attained,
					pct_occ_management,
					pct_occ_health_technologists,
					pct_white_only,
					median_housing_value,
					pct_population_under_4,
					pct_population_59,
					pct_population_1013,
					pct_population_1417,
					pct_dwelling_owner_occupied,
					pct_dwelling_renter_occupied,
					current_estimated_family_income_decile,
					bible_devotional_religious,
					volunteer_work,
					hoh_education_flag,
					hoh_occupation_flag,
					animal_welfare_contributions,
					childrens_welfare,
					cultural_welfare,
					environmental,
					health_related,
					political,
					religious_contributions,
					social_services,
					use_mac_computer,
					own_cd_rom,
					use_modem,
					own_computer,
					laser_printer,
					color_printer,
					use_internet_service,
					stock_bond_investor,
					cd_money_market_investor,
					ira_investor,
					mutual_fund_investor,
					real_estate_investor,
					crafts,
					estimated_current_home_value,
					latitude,
					longitude,
					lev_lat_long,
					fips_state_code,
					fips_county_code,
					census_tract,
					census_block_group,
					block_id,
					mcdccd_code,
					cbsa_code,
					enhancement_match_type,
					census_match_level,
					current_estimated_family_income_amount,
					current_estimated_family_income_code
)
					
	;
	INSERT INTO Seer_CTRL.dbo.Member([Member_Key],
									[Seer_Key],
									[MemberCleansedID],
									[OrganizationName],
									[OrganizationId],
									[MemberId],
									[FamilyId],
									[NumberInHousehold],
									[HeadOfHousehold],
									[MemberFirstName],
									[MemberMiddleName],
									[MemberLastName],
									[MemberNameSuffix],
									[Address1],
									[Address2],
									[AddressCity],
									[AddressState],
									[AddressPostal],
									[AddressCountry],
									[ParsedAddress1],
									[ParsedAddress2],
									[ParsedAddressCity],
									[ParsedAddressState],
									[ParsedAddressPostal],
									[ParsedAddressCountry],
									[ParsedAddressLineQuality],
									[ParsedAddressCSZQuality],
									[HomePhone],
									[Gender],
									[Ethnicity],
									[Birthdate],
									[MembershipDate],
									[Category],
									[MembershipType],
									[StaffType],
									[FullTimePartTime],
									[HourlySalary],
									[IsPrimaryMember],
									[IsEmployee],
									[IsDonor],
									[IsProgramMember],
									[IsNewMember],
									[IsHealthSeeker],
									[IsActive],
									[RemovalReason],
									[Comments],
									[RecordType],
									[MailableMember],
									[EmailableMember],
									[MailableEmployee],
									[EmailableEmployee],
									[EmailableNewMember],
									[EmailableProgramMember],
									[ProgramSiteLocation],
									[Phone],
									[EmailAddress],
									[ExactAge],
									[EstimatedAge],
									[EstimatedHouseholdIncomeAmount],
									[CountyIncomePercentile],
									[MaritalStatus],
									[Filler01],
									[Filler02],
									[Filler03],
									[Filler04],
									[Filler05],
									[Filler06],
									[Filler07],
									[Filler08],
									[Filler09],
									[HomeBusinessIndicator],
									[PresenceOfChildren03],
									[GenderOfChildren03],
									[PresenceOfChildren46],
									[GenderOfChildren46],
									[PresenceOfChildren79],
									[GenderOfChildren79],
									[PresenceOfChildren1012],
									[GenderOfChildren1012],
									[PresenceOfChildren1318],
									[GenderOfChildren1318],
									[NumberOfAdultsInHousehold],
									[Homeowner],
									[ProbableHomeowner],
									[LengthOfResidence],
									[DwellingUnitSizeCode],
									[YearBuilt],
									[MultiCoDirectMail],
									[NewsAndFinancial],
									[CurrentEstimatedMedianFamilyIncome],
									[MedianEducationYearsAttained],
									[PctOccManagement],
									[PctOccHealthTechnologists],
									[PctWhiteOnly],
									[MedianHousingValue],
									[PctPopulationUnder4],
									[PctPopulation59],
									[PctPopulation1013],
									[PctPopulation1417],
									[PctDwellingOwnerOccupied],
									[PctDwellingRenterOccupied],
									[CurrentEstimatedFamilyIncomeDecile],
									[BibleDevotionalReligious],
									[VolunteerWork],
									[HOHEducationFlag],
									[HOHOccupationFlag],
									[AnimalWelfareContributions],
									[ChildrensWelfare],
									[CulturalWelfare],
									[Environmental],
									[HealthRelated],
									[Political],
									[ReligiousContributions],
									[SocialServices],
									[UseMacComputer],
									[OwnCDRom],
									[UseModem],
									[OwnComputer],
									[LaserPrinter],
									[ColorPrinter],
									[UseInternetService],
									[StockBondInvestor],
									[CDMoneyMarketInvestor],
									[IRAInvestor],
									[MutualFundInvestor],
									[RealEstateInvestor],
									[Crafts],
									[EstimatedCurrentHomeValue],
									[Latitude],
									[Longitude],
									[LevLatLong],
									[FipsStateCode],
									[FipsCountyCode],
									[CensusTract],
									[CensusBlockGroup],
									[BlockId],
									[MCDCCDCode],
									[CBSACode],
									[EnhancementMatchType],
									[CensusMatchLevel],
									[CurrentEstimatedFamilyIncomeAmount],
									[CurrentEstimatedFamilyIncomeCode],
									[CreateDateTime]
									)
	SELECT	[Member_Key],
			[Seer_Key],
			[MemberCleansedID],
			[OrganizationName],
			[OrganizationId],
			[MemberId],
			[FamilyId],
			[NumberInHousehold],
			[HeadOfHousehold],
			[MemberFirstName],
			[MemberMiddleName],
			[MemberLastName],
			[MemberNameSuffix],
			[Address1],
			[Address2],
			[AddressCity],
			[AddressState],
			[AddressPostal],
			[AddressCountry],
			[ParsedAddress1],
			[ParsedAddress2],
			[ParsedAddressCity],
			[ParsedAddressState],
			[ParsedAddressPostal],
			[ParsedAddressCountry],
			[ParsedAddressLineQuality],
			[ParsedAddressCSZQuality],
			[HomePhone],
			[Gender],
			[Ethnicity],
			CASE WHEN LEN([Birthdate]) = 6 THEN Birthdate + '01'
				ELSE Birthdate
			END Birthdate,
			[MembershipDate],
			[Category],
			[MembershipType],
			[StaffType],
			[FullTimePartTime],
			[HourlySalary],
			[IsPrimaryMember],
			[IsEmployee],
			[IsDonor],
			[IsProgramMember],
			[IsNewMember],
			[IsHealthSeeker],
			[IsActive],
			[RemovalReason],
			[Comments],
			[RecordType],
			[MailableMember],
			[EmailableMember],
			[MailableEmployee],
			[EmailableEmployee],
			[EmailableNewMember],
			[EmailableProgramMember],
			[ProgramSiteLocation],
			[Phone],
			[EmailAddress],
			[ExactAge],
			[EstimatedAge],
			[EstimatedHouseholdIncomeAmount],
			[CountyIncomePercentile],
			[MaritalStatus],
			[Filler01],
			[Filler02],
			[Filler03],
			[Filler04],
			[Filler05],
			[Filler06],
			[Filler07],
			[Filler08],
			[Filler09],
			[HomeBusinessIndicator],
			[PresenceOfChildren03],
			[GenderOfChildren03],
			[PresenceOfChildren46],
			[GenderOfChildren46],
			[PresenceOfChildren79],
			[GenderOfChildren79],
			[PresenceOfChildren1012],
			[GenderOfChildren1012],
			[PresenceOfChildren1318],
			[GenderOfChildren1318],
			[NumberOfAdultsInHousehold],
			[Homeowner],
			[ProbableHomeowner],
			[LengthOfResidence],
			[DwellingUnitSizeCode],
			[YearBuilt],
			[MultiCoDirectMail],
			[NewsAndFinancial],
			[CurrentEstimatedMedianFamilyIncome],
			[MedianEducationYearsAttained],
			[PctOccManagement],
			[PctOccHealthTechnologists],
			[PctWhiteOnly],
			[MedianHousingValue],
			[PctPopulationUnder4],
			[PctPopulation59],
			[PctPopulation1013],
			[PctPopulation1417],
			[PctDwellingOwnerOccupied],
			[PctDwellingRenterOccupied],
			[CurrentEstimatedFamilyIncomeDecile],
			[BibleDevotionalReligious],
			[VolunteerWork],
			[HOHEducationFlag],
			[HOHOccupationFlag],
			[AnimalWelfareContributions],
			[ChildrensWelfare],
			[CulturalWelfare],
			[Environmental],
			[HealthRelated],
			[Political],
			[ReligiousContributions],
			[SocialServices],
			[UseMacComputer],
			[OwnCDRom],
			[UseModem],
			[OwnComputer],
			[LaserPrinter],
			[ColorPrinter],
			[UseInternetService],
			[StockBondInvestor],
			[CDMoneyMarketInvestor],
			[IRAInvestor],
			[MutualFundInvestor],
			[RealEstateInvestor],
			[Crafts],
			[EstimatedCurrentHomeValue],
			[Latitude],
			[Longitude],
			[LevLatLong],
			[FipsStateCode],
			[FipsCountyCode],
			[CensusTract],
			[CensusBlockGroup],
			[BlockId],
			[MCDCCDCode],
			[CBSACode],
			[EnhancementMatchType],
			[CensusMatchLevel],
			[CurrentEstimatedFamilyIncomeAmount],
			[CurrentEstimatedFamilyIncomeCode],
			[CreateDateTime]
			
	FROM	Seer_STG.dbo.Member

	WHERE	ISDATE(COALESCE(MembershipDate, 'JAN 01 1900')) = 0
	;
END